name: lx128_p3
channels:
  - defaults
dependencies:
  - altgraph=0.17
  - appdirs=1.4.4
  - astroid=2.3.2
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - backcall=0.1.0
  - black=19.10b0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - click=8.0.1
  - colorama=0.4.1
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - future=0.18.2
  - icu=58.2
  - importlib-metadata=3.10.0
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.3
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.4.1
  - macholib=1.14
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - notebook=6.0.2
  - numpy=1.17.3
  - numpy-base=1.17.3
  - openssl=1.1.1k
  - packaging=20.3
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pathspec=0.7.0
  - pefile=2019.4.18
  - pickleshare=0.7.5
  - pip=19.3.1
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - py=1.8.1
  - pycodestyle=2.5.0
  - pycryptodome=3.9.9
  - pygments=2.4.2
  - pyinstaller=3.6
  - pylint=2.4.3
  - pyparsing=2.4.5
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - pytest=5.4.2
  - python=3.7.5
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - regex=2021.8.3
  - rope=0.14.0
  - scipy=1.3.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=41.6.0
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - toml=0.10.2
  - tornado=6.0.3
  - traitlets=4.3.3
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - wrapt=1.11.2
  - wxpython=4.0.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
      - comtypes==1.1.7
      - debugpy==1.0.0b5
      - pyteomics==4.1.2
      - schedule==1.1.0
